-- MySQL Script generated by MySQL Workbench
-- Sun Aug 19 17:22:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `email` VARCHAR(25) NOT NULL,
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `pass` VARCHAR(40) NOT NULL,
  `role` TINYINT(5) NOT NULL DEFAULT '1' COMMENT 'User role. TinyInt type is used for future scalability.\n0 for admin\n1 for HR',
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `id_UNIQUE` (`idLogin` ASC),
  UNIQUE INDEX `login_email_uindex` (`email` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8
COMMENT = 'Данные для захода в систему';


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idAdmin` INT(11) NOT NULL,
  `fullName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC),
  CONSTRAINT `idLoginLoginTB`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `mydb`.`login` (`idLogin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'База админов. Уровень доступа проверяется по наличию айди в базе админов.';


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `idCompany` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название компании',
  `niche` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Занимаемая ниша компании',
  `location` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Месторасположение',
  `headCount` INT(11) NULL DEFAULT NULL COMMENT 'Количество сотрудников',
  `offCompId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `idCompany_UNIQUE` (`idCompany` ASC),
  UNIQUE INDEX `offCompId_UNIQUE` (`offCompId` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8
COMMENT = 'Данные о компании в которых работают сотрудники.';


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `idEmployee` INT(11) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL COMMENT 'Имя',
  `lName` VARCHAR(45) NOT NULL COMMENT 'Фамилия',
  `mName` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Отвечество',
  `ssn` INT(11) NOT NULL COMMENT 'Номер социального страхования или иной уникальный идентификационный номер документа обязательного при приёме на работу',
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `id_UNIQUE` (`idEmployee` ASC),
  UNIQUE INDEX `SSN_UNIQUE` (`ssn` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8
COMMENT = 'Сотрудники компаний';


-- -----------------------------------------------------
-- Table `mydb`.`hrhead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hrhead` (
  `idHRhead` INT(11) NOT NULL,
  `fName` VARCHAR(20) NOT NULL COMMENT 'Имя',
  `mName` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Отчество',
  `lName` VARCHAR(20) NOT NULL COMMENT 'Фамилия',
  `idCompany` INT(11) NULL DEFAULT NULL COMMENT 'Компания в которой работает HR',
  `SSN` INT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`idHRhead`),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC),
  INDEX `id_idx` (`idHRhead` ASC),
  INDEX `idCompany_idx` (`idCompany` ASC),
  CONSTRAINT `idLogin`
    FOREIGN KEY (`idHRhead`)
    REFERENCES `mydb`.`login` (`idLogin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Содержит HR сотрудников работающих в компаниях. Каждый сотрудник может работать на разные компании.';


-- -----------------------------------------------------
-- Table `mydb`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`history` (
  `yearEmployed` SMALLINT(4) NULL DEFAULT NULL COMMENT 'Дата приёма на работу',
  `yearTerminated` SMALLINT(4) NULL DEFAULT NULL COMMENT 'Дата увольнения',
  `rating1` TINYINT(1) NOT NULL COMMENT 'Рейтинг от 0 до 10',
  `rating2` TINYINT(1) NOT NULL,
  `rating3` TINYINT(1) NOT NULL,
  `rating4` TINYINT(1) NOT NULL,
  `rating5` TINYINT(1) NOT NULL,
  `totalRating` DOUBLE NOT NULL COMMENT 'Средний рейтинг основывается на среднем значении рейтингов.',
  `hireAgain` TINYINT(4) NULL DEFAULT NULL COMMENT 'Запрос наймёт ли данный HR данного сотрудника ещё раз.',
  `idCompany` INT(11) NOT NULL,
  `idHR` INT(11) NOT NULL,
  `idEmployee` INT(11) NOT NULL,
  `confirmed` TINYINT(2) NULL DEFAULT '0',
  `ratingID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ratingID`),
  INDEX `idCompany_idx` (`idCompany` ASC),
  INDEX `idHRhead_idx` (`idHR` ASC),
  INDEX `empIDFK` (`idEmployee` ASC),
  CONSTRAINT `idCompany`
    FOREIGN KEY (`idCompany`)
    REFERENCES `mydb`.`company` (`idCompany`),
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`employee` (`idEmployee`),
  CONSTRAINT `idHRhead`
    FOREIGN KEY (`idHR`)
    REFERENCES `mydb`.`hrhead` (`idHRhead`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8
COMMENT = 'Таблица для хранения отзывов и данных о каждом месте работы сотрудников. Таблица так же связана с таблицей сотрудников, компаний и HR.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
